// src/data.ts

export type Category =
  | "Web Development"
  | "Programming Languages & Software Engineering"
  | "Data Science & Analytics"
  | "Artificial Intelligence & Machine Learning"
  | "Cloud Computing & DevOps"
  | "Cybersecurity & Networking"
  | "Mobile App Development"
  | "Databases & Big Data"
  | "Algorithms & Data Structures"
  | "IT Fundamentals & Support"
  | "Software Architecture & Design Patterns"
  | "Specialized Computer Science Topics";

export interface Course {
  id: string;
  title: string;
  platform: string;
  description: string;
  link: string;
  rating: "Recommend" | "Do Not Recommend" | "Depends";
  recommendCount: number;
  doNotRecommendCount: number;
  thumbnail: string;
  instructor: string;
  categories: Category[];
  uploadDate: string;
}

export const courses: Course[] = [
  {
    id: "1",
    title: "React for Beginners",
    platform: "Udemy",
    description:
      "Learn the basics of React and start building interactive web applications.",
    link: "https://www.udemy.com/course/react-for-beginners/",
    rating: "Recommend",
    recommendCount: 45,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "John Doe",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-08-01",
  },
  {
    id: "2",
    title: "Advanced Python Programming",
    platform: "LinkedIn Learning",
    description: "Deep dive into advanced Python programming techniques.",
    link: "https://www.linkedin.com/learning/advanced-python-programming/",
    rating: "Depends",
    recommendCount: 30,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jane Smith",
    categories: ["Programming Languages & Software Engineering"],
    uploadDate: "2024-07-15",
  },
  {
    id: "3",
    title: "Introduction to Machine Learning",
    platform: "Coursera",
    description:
      "A beginner-friendly course on the basics of machine learning.",
    link: "https://www.coursera.org/learn/machine-learning/",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrew Ng",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-06-25",
  },
  {
    id: "4",
    title: "Full-Stack Web Development with React and Node.js",
    platform: "Udemy",
    description: "Become a full-stack web developer using React and Node.js.",
    link: "https://www.udemy.com/course/full-stack-web-development-with-react-and-nodejs/",
    rating: "Do Not Recommend",
    recommendCount: 10,
    doNotRecommendCount: 40,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Sarah Lee",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-10",
  },
  {
    id: "5",
    title: "Java Programming and Software Engineering Fundamentals",
    platform: "Coursera",
    description:
      "A beginner-friendly specialization that covers Java programming, software development processes, and foundational computer science concepts.",
    link: "https://www.coursera.org/specializations/java-programming",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Duke University",
    categories: [
      "Programming Languages & Software Engineering",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2023-12-15",
  },
  {
    id: "6",
    title: "Data Structures and Algorithms Specialization",
    platform: "Coursera",
    description:
      "Learn the basics of data structures and algorithms to prepare for technical interviews and improve programming efficiency.",
    link: "https://www.coursera.org/specializations/data-structures-algorithms",
    rating: "Recommend",
    recommendCount: 110,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of California San Diego",
    categories: [
      "Algorithms & Data Structures",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-01",
  },
  {
    id: "7",
    title: "Full-Stack Web Development with Angular and Spring Boot",
    platform: "Udemy",
    description:
      "Learn full-stack web development using Angular for the front-end and Spring Boot for the back-end.",
    link: "https://www.udemy.com/course/full-stack-web-development-with-angular-and-spring-boot/",
    rating: "Recommend",
    recommendCount: 70,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Chad Darby",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-04-10",
  },
  {
    id: "8",
    title: "Clean Code: Writing Code for Humans",
    platform: "Pluralsight",
    description:
      "Learn the principles of writing clean, maintainable, and scalable code.",
    link: "https://www.pluralsight.com/courses/clean-code-humans",
    rating: "Depends",
    recommendCount: 40,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Cory House",
    categories: [
      "Programming Languages & Software Engineering",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-03-05",
  },
  {
    id: "9",
    title: "Machine Learning Specialization",
    platform: "Coursera",
    description:
      "Comprehensive coverage of machine learning concepts, including supervised and unsupervised learning, neural networks, and deep learning.",
    link: "https://www.coursera.org/specializations/machine-learning-introduction",
    rating: "Recommend",
    recommendCount: 130,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrew Ng",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-01-20",
  },
  {
    id: "10",
    title: "Microservices with Node JS and React",
    platform: "Udemy",
    description:
      "Build, deploy, and scale a microservices architecture using Node.js, React, Docker, and Kubernetes.",
    link: "https://www.udemy.com/course/microservices-with-node-js-and-react/",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephen Grider",
    categories: [
      "Web Development",
      "Software Architecture & Design Patterns",
      "Cloud Computing & DevOps",
    ],
    uploadDate: "2024-03-12",
  },
  {
    id: "11",
    title: "CS50's Introduction to Computer Science",
    platform: "edX",
    description:
      "Harvard's popular introductory course on computer science and programming concepts.",
    link: "https://www.edx.org/course/cs50s-introduction-to-computer-science",
    rating: "Recommend",
    recommendCount: 150,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "David J. Malan",
    categories: [
      "Programming Languages & Software Engineering",
      "Algorithms & Data Structures",
      "IT Fundamentals & Support",
    ],
    uploadDate: "2023-11-20",
  },
  {
    id: "12",
    title: "The Complete Web Developer Course 2.0",
    platform: "Udemy",
    description:
      "A comprehensive guide to web development, covering HTML, CSS, JavaScript, PHP, Python, MySQL, and more.",
    link: "https://www.udemy.com/course/the-complete-web-developer-course-2/",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Rob Percival",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
      "Databases & Big Data",
    ],
    uploadDate: "2024-05-22",
  },
  {
    id: "13",
    title: "Design Patterns in Java",
    platform: "Pluralsight",
    description:
      "Master the most common design patterns in Java to write more robust and flexible code.",
    link: "https://www.pluralsight.com/courses/design-patterns-java",
    rating: "Depends",
    recommendCount: 60,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Bryan Hansen",
    categories: [
      "Programming Languages & Software Engineering",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-02-18",
  },
  {
    id: "14",
    title: "Cloud Architecture with Google Cloud",
    platform: "Coursera",
    description:
      "Learn cloud computing basics and how to design, develop, and manage secure, scalable cloud solutions with Google Cloud.",
    link: "https://www.coursera.org/specializations/cloud-architecture-google-cloud",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Google Cloud",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-06-05",
  },
  {
    id: "15",
    title: "Introduction to DevOps and Site Reliability Engineering",
    platform: "Coursera",
    description:
      "Explore DevOps practices and learn to manage infrastructure and code deployment with a focus on SRE principles.",
    link: "https://www.coursera.org/learn/devops-site-reliability-engineering",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Google Cloud",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-04-01",
  },
  {
    id: "16",
    title: "Kubernetes for the Absolute Beginners - Hands-on",
    platform: "Udemy",
    description: "Learn Kubernetes from scratch with hands-on labs.",
    link: "https://www.udemy.com/course/kubernetes-for-the-absolute-beginners-hands-on/",
    rating: "Recommend",
    recommendCount: 75,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Mumshad Mannambeth",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-02-27",
  },
  {
    id: "17",
    title: "Git & GitHub - The Practical Guide",
    platform: "Udemy",
    description:
      "Master Git and GitHub with a focus on practical scenarios and project-based learning.",
    link: "https://www.udemy.com/course/git-github-the-practical-guide/",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Maximilian Schwarzmüller",
    categories: [
      "Programming Languages & Software Engineering",
      "IT Fundamentals & Support",
    ],
    uploadDate: "2024-01-05",
  },
  {
    id: "18",
    title: "The Complete SQL Bootcamp 2024: Go from Zero to Hero",
    platform: "Udemy",
    description:
      "Learn SQL for data science and database management, covering everything from basic queries to complex data analysis.",
    link: "https://www.udemy.com/course/the-complete-sql-bootcamp/",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Portilla",
    categories: ["Databases & Big Data", "Data Science & Analytics"],
    uploadDate: "2024-03-18",
  },
  {
    id: "19",
    title: "React Native - The Practical Guide",
    platform: "Udemy",
    description:
      "Build cross-platform mobile apps with React Native using a practical, hands-on approach.",
    link: "https://www.udemy.com/course/react-native-the-practical-guide/",
    rating: "Depends",
    recommendCount: 65,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Maximilian Schwarzmüller",
    categories: [
      "Mobile App Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-14",
  },
  {
    id: "20",
    title: "Introduction to Cyber Security Specialization",
    platform: "Coursera",
    description:
      "Gain a foundational understanding of cybersecurity principles, including threat analysis and defense strategies.",
    link: "https://www.coursera.org/specializations/intro-cyber-security",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Washington",
    categories: ["Cybersecurity & Networking", "IT Fundamentals & Support"],
    uploadDate: "2024-01-12",
  },
  {
    id: "21",
    title: "Docker and Kubernetes: The Complete Guide",
    platform: "Udemy",
    description:
      "Master Docker and Kubernetes by building, deploying, and managing applications in real-world projects.",
    link: "https://www.udemy.com/course/docker-and-kubernetes-the-complete-guide/",
    rating: "Recommend",
    recommendCount: 110,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephen Grider",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-05-30",
  },
  {
    id: "22",
    title: "Python for Everybody Specialization",
    platform: "Coursera",
    description:
      "An introduction to Python programming, focusing on data analysis and building web applications.",
    link: "https://www.coursera.org/specializations/python",
    rating: "Recommend",
    recommendCount: 200,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Charles Russel Severance",
    categories: [
      "Databases & Big Data",
      "Data Science & Analytics",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-01-01",
  },
  {
    id: "23",
    title: "Learn DevOps: Infrastructure Automation With Terraform",
    platform: "Udemy",
    description:
      "Learn how to automate your infrastructure using Terraform, a popular IaC (Infrastructure as Code) tool.",
    link: "https://www.udemy.com/course/learn-devops-infrastructure-automation-with-terraform/",
    rating: "Recommend",
    recommendCount: 75,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Edward Viaene",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-04-02",
  },
  {
    id: "24",
    title: "JavaScript: Understanding the Weird Parts",
    platform: "Udemy",
    description:
      "Deep dive into the inner workings of JavaScript to write better and more maintainable code.",
    link: "https://www.udemy.com/course/understand-javascript/",
    rating: "Recommend",
    recommendCount: 135,
    doNotRecommendCount: 7,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Anthony Alicea",
    categories: [
      "Programming Languages & Software Engineering",
      "Web Development",
    ],
    uploadDate: "2024-03-25",
  },
  {
    id: "25",
    title: "The Complete Guide to Angular: Beginner to Advanced",
    platform: "Udemy",
    description:
      "Comprehensive guide to Angular, covering everything from the basics to advanced topics.",
    link: "https://www.udemy.com/course/the-complete-guide-to-angular/",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 9,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Maximilian Schwarzmüller",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-10",
  },
  {
    id: "26",
    title: "Deep Learning Specialization",
    platform: "Coursera",
    description:
      "Gain a solid understanding of deep learning concepts, including neural networks, convolutional networks, and sequence models.",
    link: "https://www.coursera.org/specializations/deep-learning",
    rating: "Recommend",
    recommendCount: 150,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrew Ng",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2023-12-07",
  },
  {
    id: "27",
    title: "Mastering Data Structures & Algorithms using C and C++",
    platform: "Udemy",
    description:
      "Learn data structures and algorithms in C and C++ to enhance problem-solving and programming skills.",
    link: "https://www.udemy.com/course/datastructurescncpp/",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 22,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Abdul Bari",
    categories: [
      "Algorithms & Data Structures",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-11",
  },
  {
    id: "28",
    title:
      "Introduction to TensorFlow for Artificial Intelligence, Machine Learning, and Deep Learning",
    platform: "Coursera",
    description:
      "Learn TensorFlow and how to use it for AI, machine learning, and deep learning projects.",
    link: "https://www.coursera.org/learn/introduction-tensorflow",
    rating: "Recommend",
    recommendCount: 130,
    doNotRecommendCount: 17,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Laurence Moroney",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-01-15",
  },
  {
    id: "29",
    title: "Spring Framework Master Class - Java Spring the Modern Way",
    platform: "Udemy",
    description:
      "Master the core concepts of Spring Framework and build modern, scalable applications in Java.",
    link: "https://www.udemy.com/course/spring-framework-master-class/",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ranga Karanam",
    categories: [
      "Programming Languages & Software Engineering",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-04-22",
  },
  {
    id: "30",
    title: "Complete Guide to Elasticsearch",
    platform: "Udemy",
    description:
      "Learn Elasticsearch from scratch and use it to build powerful search and analytics engines.",
    link: "https://www.udemy.com/course/elasticsearch-complete-guide/",
    rating: "Depends",
    recommendCount: 50,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Bo Andersen",
    categories: [
      "Databases & Big Data",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-05-08",
  },
  {
    id: "31",
    title: "AWS Certified Solutions Architect - Associate 2024",
    platform: "Udemy",
    description:
      "Prepare for the AWS Solutions Architect certification with this comprehensive course on AWS services and architecture.",
    link: "https://www.udemy.com/course/aws-certified-solutions-architect-associate/",
    rating: "Recommend",
    recommendCount: 175,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephane Maarek",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-03-14",
  },
  {
    id: "32",
    title: "The Complete Cyber Security Course: Hackers Exposed!",
    platform: "Udemy",
    description:
      "Learn the essentials of cybersecurity, including how to protect your personal data and defend against hackers.",
    link: "https://www.udemy.com/course/the-complete-cyber-security-course-volume-1-hackers-exposed/",
    rating: "Recommend",
    recommendCount: 110,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Nathan House",
    categories: ["Cybersecurity & Networking", "IT Fundamentals & Support"],
    uploadDate: "2024-01-22",
  },
  {
    id: "33",
    title: "The Complete Guide to SQL and MySQL",
    platform: "Udemy",
    description:
      "A beginner-to-advanced guide on SQL and MySQL, focusing on database management and data manipulation techniques.",
    link: "https://www.udemy.com/course/the-complete-guide-to-sql-and-mysql/",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Mosh Hamedani",
    categories: [
      "Databases & Big Data",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-15",
  },
  {
    id: "34",
    title: "Go: The Complete Developer's Guide (Golang)",
    platform: "Udemy",
    description:
      "Learn the Go programming language from the ground up with hands-on examples and projects.",
    link: "https://www.udemy.com/course/go-the-complete-developers-guide/",
    rating: "Recommend",
    recommendCount: 75,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephen Grider",
    categories: ["Programming Languages & Software Engineering"],
    uploadDate: "2024-02-20",
  },
  {
    id: "35",
    title: "Python for Data Science and Machine Learning Bootcamp",
    platform: "Udemy",
    description:
      "Learn Python specifically for data science and machine learning applications, with practical, real-world examples.",
    link: "https://www.udemy.com/course/python-for-data-science-and-machine-learning-bootcamp/",
    rating: "Recommend",
    recommendCount: 140,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Portilla",
    categories: [
      "Data Science & Analytics",
      "Artificial Intelligence & Machine Learning",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-30",
  },
  {
    id: "36",
    title: "Full-Stack Web Development with Ruby on Rails",
    platform: "Udemy",
    description:
      "Learn full-stack web development using Ruby on Rails, covering both backend and frontend skills.",
    link: "https://www.udemy.com/course/full-stack-web-development-with-ruby-on-rails/",
    rating: "Recommend",
    recommendCount: 65,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jordan Hudgens",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-04-18",
  },
  {
    id: "37",
    title: "Introduction to Cloud Computing with Amazon Web Services",
    platform: "LinkedIn Learning",
    description:
      "Get started with cloud computing using Amazon Web Services (AWS), covering core services and cloud concepts.",
    link: "https://www.linkedin.com/learning/introduction-to-cloud-computing-with-amazon-web-services",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "David Linthicum",
    categories: ["Cloud Computing & DevOps", "IT Fundamentals & Support"],
    uploadDate: "2024-02-05",
  },
  {
    id: "38",
    title: "Practical Data Science with Python",
    platform: "Coursera",
    description:
      "Learn data science concepts and techniques with Python, focusing on practical applications and real-world projects.",
    link: "https://www.coursera.org/learn/practical-data-science-python",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Colorado Boulder",
    categories: [
      "Data Science & Analytics",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-02",
  },
  {
    id: "39",
    title: "Introduction to Algorithms",
    platform: "edX",
    description:
      "An MIT course covering fundamental algorithms, including sorting, searching, dynamic programming, and graph algorithms.",
    link: "https://www.edx.org/course/introduction-to-algorithms",
    rating: "Recommend",
    recommendCount: 150,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Charles Leiserson",
    categories: [
      "Algorithms & Data Structures",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-08",
  },
  {
    id: "40",
    title: "React Native: Advanced Concepts",
    platform: "Udemy",
    description:
      "Take your React Native skills to the next level by learning advanced concepts and techniques for building mobile apps.",
    link: "https://www.udemy.com/course/react-native-advanced/",
    rating: "Depends",
    recommendCount: 60,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephen Grider",
    categories: [
      "Mobile App Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-01-29",
  },
  {
    id: "41",
    title: "The Complete Node.js Developer Course (3rd Edition)",
    platform: "Udemy",
    description:
      "Learn Node.js by building real-world applications, covering everything from basics to advanced topics.",
    link: "https://www.udemy.com/course/the-complete-nodejs-developer-course-2/",
    rating: "Recommend",
    recommendCount: 145,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrew Mead",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-25",
  },
  {
    id: "42",
    title: "Java Programming Masterclass for Software Developers",
    platform: "Udemy",
    description:
      "Master Java programming from beginner to advanced level, including core Java, JavaFX, and Spring.",
    link: "https://www.udemy.com/course/java-the-complete-java-developer-course/",
    rating: "Recommend",
    recommendCount: 170,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Tim Buchalka",
    categories: [
      "Programming Languages & Software Engineering",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-04-07",
  },
  {
    id: "43",
    title: "Introduction to Software Product Management",
    platform: "Coursera",
    description:
      "Learn the basics of software product management and the role of a software product manager.",
    link: "https://www.coursera.org/learn/introduction-to-software-product-management",
    rating: "Recommend",
    recommendCount: 60,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Alberta",
    categories: [
      "Software Architecture & Design Patterns",
      "IT Fundamentals & Support",
    ],
    uploadDate: "2024-01-02",
  },
  {
    id: "44",
    title: "Computer Vision Basics",
    platform: "Coursera",
    description:
      "Understand the basics of computer vision, including image processing, detection, and classification.",
    link: "https://www.coursera.org/learn/computer-vision-basics",
    rating: "Recommend",
    recommendCount: 75,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University at Buffalo",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-03-01",
  },
  {
    id: "45",
    title: "Practical Guide to System Design",
    platform: "Udemy",
    description:
      "Learn system design principles and prepare for technical interviews with practical, real-world examples.",
    link: "https://www.udemy.com/course/practical-guide-to-system-design/",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Junaid Ahmed",
    categories: [
      "Software Architecture & Design Patterns",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-14",
  },
  {
    id: "46",
    title: "Introduction to Artificial Intelligence (AI)",
    platform: "Coursera",
    description:
      "Explore the world of AI with an introductory course covering foundational AI concepts and techniques.",
    link: "https://www.coursera.org/learn/introduction-to-ai",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "IBM",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-01-11",
  },
  {
    id: "47",
    title: "Programming for Everybody (Getting Started with Python)",
    platform: "Coursera",
    description:
      "Start learning programming with Python in this introductory course for beginners.",
    link: "https://www.coursera.org/learn/python",
    rating: "Recommend",
    recommendCount: 200,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Charles Severance",
    categories: [
      "Programming Languages & Software Engineering",
      "IT Fundamentals & Support",
    ],
    uploadDate: "2024-04-09",
  },
  {
    id: "48",
    title: "Introduction to DevOps: Transform Your Organization",
    platform: "LinkedIn Learning",
    description:
      "Understand DevOps principles and how to implement DevOps in your organization to improve software delivery.",
    link: "https://www.linkedin.com/learning/introduction-to-devops-transform-your-organization",
    rating: "Depends",
    recommendCount: 55,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ernest Mueller",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-03-16",
  },
  {
    id: "49",
    title: "Software Processes and Agile Practices",
    platform: "Coursera",
    description:
      "Learn about software development processes and agile methodologies to manage software projects effectively.",
    link: "https://www.coursera.org/learn/software-processes-and-agile-practices",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Alberta",
    categories: [
      "Software Architecture & Design Patterns",
      "IT Fundamentals & Support",
    ],
    uploadDate: "2024-05-05",
  },
  {
    id: "50",
    title: "C# Basics for Beginners: Learn C# Fundamentals by Coding",
    platform: "Udemy",
    description:
      "A beginner-friendly course on C# programming, focusing on the basics and practical coding exercises.",
    link: "https://www.udemy.com/course/csharp-tutorial-for-beginners/",
    rating: "Recommend",
    recommendCount: 70,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Mosh Hamedani",
    categories: ["Programming Languages & Software Engineering"],
    uploadDate: "2024-02-06",
  },
  {
    id: "51",
    title:
      "Building Scalable Java Microservices with Spring Boot and Spring Cloud",
    platform: "Coursera",
    description:
      "Learn to build scalable microservices with Java, Spring Boot, and Spring Cloud.",
    link: "https://www.coursera.org/learn/building-scalable-java-microservices-with-spring-boot-and-spring-cloud",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Google Cloud",
    categories: [
      "Programming Languages & Software Engineering",
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-04-20",
  },
  {
    id: "52",
    title: "Linux Command Line Basics",
    platform: "Udemy",
    description:
      "Learn the basics of Linux command line, covering essential commands and shell scripting.",
    link: "https://www.udemy.com/course/linux-command-line-basics/",
    rating: "Recommend",
    recommendCount: 65,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jason Cannon",
    categories: ["IT Fundamentals & Support", "Cloud Computing & DevOps"],
    uploadDate: "2024-03-21",
  },
  {
    id: "53",
    title: "Kotlin for Java Developers",
    platform: "Coursera",
    description:
      "Transition from Java to Kotlin with ease and learn Kotlin's modern programming features.",
    link: "https://www.coursera.org/learn/kotlin-for-java-developers",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 7,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "JetBrains",
    categories: [
      "Programming Languages & Software Engineering",
      "Mobile App Development",
    ],
    uploadDate: "2024-04-28",
  },
  {
    id: "54",
    title: "RESTful Web Services, Java, Spring Boot, Spring MVC, and JPA",
    platform: "Udemy",
    description:
      "Build RESTful web services using Java, Spring Boot, and Spring MVC.",
    link: "https://www.udemy.com/course/restful-web-services-with-spring-framework/",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ranga Karanam",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-01-30",
  },
  {
    id: "55",
    title: "Modern React with Redux [2024 Update]",
    platform: "Udemy",
    description:
      "Master React and Redux with modern features and best practices in 2024.",
    link: "https://www.udemy.com/course/react-redux/",
    rating: "Recommend",
    recommendCount: 130,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephen Grider",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-03",
  },
  {
    id: "56",
    title: "Data Science and Machine Learning Bootcamp with R",
    platform: "Udemy",
    description:
      "Learn data science and machine learning with R, focusing on practical applications and real-world datasets.",
    link: "https://www.udemy.com/course/data-science-and-machine-learning-bootcamp-with-r/",
    rating: "Recommend",
    recommendCount: 100,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Portilla",
    categories: [
      "Data Science & Analytics",
      "Artificial Intelligence & Machine Learning",
    ],
    uploadDate: "2024-03-12",
  },
  {
    id: "57",
    title: "Cybersecurity for Beginners",
    platform: "LinkedIn Learning",
    description:
      "Start learning cybersecurity fundamentals, including threats, vulnerabilities, and defense strategies.",
    link: "https://www.linkedin.com/learning/cybersecurity-for-beginners",
    rating: "Recommend",
    recommendCount: 65,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Malcolm Shore",
    categories: ["Cybersecurity & Networking", "IT Fundamentals & Support"],
    uploadDate: "2024-02-23",
  },
  {
    id: "58",
    title: "Complete Python Web Course: Build 8 Python Web Apps",
    platform: "Udemy",
    description:
      "Learn Python web development by building 8 real-world web applications using Django, Flask, and more.",
    link: "https://www.udemy.com/course/complete-python-web-course-build-8-python-web-apps/",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Salvatierra",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-07",
  },
  {
    id: "59",
    title: "Big Data Essentials: HDFS, MapReduce and Spark RDD",
    platform: "Coursera",
    description:
      "Learn big data concepts, including HDFS, MapReduce, and Spark, to handle and analyze large datasets.",
    link: "https://www.coursera.org/learn/big-data-essentials",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Yandex",
    categories: ["Databases & Big Data", "Data Science & Analytics"],
    uploadDate: "2024-02-11",
  },
  {
    id: "60",
    title: "Essential Google Cloud Infrastructure: Foundation",
    platform: "Coursera",
    description:
      "Learn the basics of Google Cloud infrastructure, including networking, security, and computing services.",
    link: "https://www.coursera.org/learn/gcp-infrastructure-foundation",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Google Cloud",
    categories: ["Cloud Computing & DevOps", "IT Fundamentals & Support"],
    uploadDate: "2024-01-18",
  },
  {
    id: "61",
    title: "Introduction to Data Science in Python",
    platform: "Coursera",
    description:
      "Learn the basics of data science using Python, including data manipulation, analysis, and visualization.",
    link: "https://www.coursera.org/learn/python-data-analysis",
    rating: "Recommend",
    recommendCount: 110,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Michigan",
    categories: [
      "Data Science & Analytics",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-05",
  },
  {
    id: "62",
    title: "Python for Data Analysis and Visualization",
    platform: "Udemy",
    description:
      "Master data analysis and visualization techniques using Python libraries like Pandas, Matplotlib, and Seaborn.",
    link: "https://www.udemy.com/course/python-for-data-analysis-and-visualization/",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Portilla",
    categories: [
      "Data Science & Analytics",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-28",
  },
  {
    id: "63",
    title: "The Web Developer Bootcamp 2024",
    platform: "Udemy",
    description:
      "A comprehensive course covering everything you need to know to become a web developer in 2024.",
    link: "https://www.udemy.com/course/the-web-developer-bootcamp/",
    rating: "Recommend",
    recommendCount: 190,
    doNotRecommendCount: 25,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Colt Steele",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-01-27",
  },
  {
    id: "64",
    title: "Master the Coding Interview: Data Structures + Algorithms",
    platform: "Udemy",
    description:
      "Prepare for coding interviews by learning data structures and algorithms in a practical, hands-on manner.",
    link: "https://www.udemy.com/course/master-the-coding-interview-data-structures-algorithms/",
    rating: "Recommend",
    recommendCount: 150,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrei Neagoie",
    categories: [
      "Algorithms & Data Structures",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-12",
  },
  {
    id: "65",
    title:
      "Building a Web App with ASP.NET Core, MVC, Entity Framework, and Bootstrap",
    platform: "Udemy",
    description:
      "Learn to build web applications using ASP.NET Core, MVC, Entity Framework, and Bootstrap.",
    link: "https://www.udemy.com/course/building-a-web-app-with-aspnet-core-mvc-entity-framework-and-bootstrap/",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Mosh Hamedani",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-15",
  },
  {
    id: "66",
    title: "Cloud Computing Basics (Cloud 101)",
    platform: "Coursera",
    description:
      "Understand the basics of cloud computing, including key concepts, benefits, and deployment models.",
    link: "https://www.coursera.org/learn/cloud-computing-basics",
    rating: "Recommend",
    recommendCount: 70,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "LearnQuest",
    categories: ["Cloud Computing & DevOps", "IT Fundamentals & Support"],
    uploadDate: "2024-01-08",
  },
  {
    id: "67",
    title: "Advanced CSS and Sass: Flexbox, Grid, Animations and More!",
    platform: "Udemy",
    description:
      "Master advanced CSS techniques, including Flexbox, Grid, and animations, to create responsive designs.",
    link: "https://www.udemy.com/course/advanced-css-and-sass/",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 7,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jonas Schmedtmann",
    categories: ["Web Development"],
    uploadDate: "2024-04-03",
  },
  {
    id: "68",
    title: "React Native for Beginners",
    platform: "LinkedIn Learning",
    description:
      "Get started with React Native and learn how to build cross-platform mobile apps from scratch.",
    link: "https://www.linkedin.com/learning/react-native-for-beginners",
    rating: "Recommend",
    recommendCount: 65,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ray Villalobos",
    categories: [
      "Mobile App Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-12",
  },
  {
    id: "69",
    title: "Introduction to Containers w/ Docker, Kubernetes & OpenShift",
    platform: "Coursera",
    description:
      "Learn about container technologies, including Docker, Kubernetes, and OpenShift, and their applications in DevOps.",
    link: "https://www.coursera.org/learn/containers-docker-kubernetes-openshift",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "IBM",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-05-10",
  },
  {
    id: "70",
    title: "JavaScript Algorithms and Data Structures Masterclass",
    platform: "Udemy",
    description:
      "Learn algorithms and data structures in JavaScript to solve complex problems and excel in technical interviews.",
    link: "https://www.udemy.com/course/js-algorithms-and-data-structures-masterclass/",
    rating: "Recommend",
    recommendCount: 140,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Colt Steele",
    categories: [
      "Algorithms & Data Structures",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-04-22",
  },
  {
    id: "71",
    title: "DevOps Foundations",
    platform: "LinkedIn Learning",
    description:
      "Understand the core principles of DevOps and how to implement DevOps practices in your organization.",
    link: "https://www.linkedin.com/learning/devops-foundations",
    rating: "Recommend",
    recommendCount: 70,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ernest Mueller",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-02-04",
  },
  {
    id: "72",
    title:
      "Complete Guide to Building Microservices with Spring Boot and Spring Cloud",
    platform: "Udemy",
    description:
      "Learn to build, deploy, and scale microservices using Spring Boot and Spring Cloud.",
    link: "https://www.udemy.com/course/complete-guide-to-building-microservices-with-spring-boot-and-spring-cloud/",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ranga Karanam",
    categories: [
      "Software Architecture & Design Patterns",
      "Programming Languages & Software Engineering",
      "Cloud Computing & DevOps",
    ],
    uploadDate: "2024-03-09",
  },
  {
    id: "73",
    title: "MongoDB - The Complete Developer's Guide 2024",
    platform: "Udemy",
    description:
      "Master MongoDB and learn how to use it for modern database management in applications.",
    link: "https://www.udemy.com/course/mongodb-the-complete-developers-guide/",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Maximilian Schwarzmüller",
    categories: [
      "Databases & Big Data",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-04-14",
  },
  {
    id: "74",
    title: "The Complete Ethical Hacking Course: Beginner to Advanced",
    platform: "Udemy",
    description:
      "Learn ethical hacking from scratch, covering networking, security, and hacking tools.",
    link: "https://www.udemy.com/course/the-complete-ethical-hacking-course-beginner-to-advanced/",
    rating: "Recommend",
    recommendCount: 100,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Ermin Kreponic",
    categories: ["Cybersecurity & Networking", "IT Fundamentals & Support"],
    uploadDate: "2024-05-08",
  },
  {
    id: "75",
    title: "The Complete JavaScript Course 2024: From Zero to Expert!",
    platform: "Udemy",
    description:
      "Become a JavaScript expert by learning everything from basics to advanced concepts in a practical, hands-on approach.",
    link: "https://www.udemy.com/course/the-complete-javascript-course/",
    rating: "Recommend",
    recommendCount: 200,
    doNotRecommendCount: 20,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jonas Schmedtmann",
    categories: [
      "Programming Languages & Software Engineering",
      "Web Development",
    ],
    uploadDate: "2024-02-15",
  },
  {
    id: "76",
    title: "Advanced Machine Learning Specialization",
    platform: "Coursera",
    description:
      "Deep dive into advanced machine learning techniques, including deep learning, reinforcement learning, and more.",
    link: "https://www.coursera.org/specializations/aml",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "National Research University Higher School of Economics",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-03-29",
  },
  {
    id: "77",
    title: "JavaScript: The Hard Parts, v2",
    platform: "Frontend Masters",
    description:
      "Explore the challenging parts of JavaScript and understand how to use closures, callbacks, and async/await effectively.",
    link: "https://frontendmasters.com/courses/javascript-hard-parts-v2/",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 5,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Will Sentance",
    categories: [
      "Programming Languages & Software Engineering",
      "Web Development",
    ],
    uploadDate: "2024-04-19",
  },
  {
    id: "78",
    title: "Mastering Kubernetes",
    platform: "Udemy",
    description:
      "Become proficient in Kubernetes by learning to deploy, manage, and scale containerized applications.",
    link: "https://www.udemy.com/course/mastering-kubernetes/",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Gourav Shah",
    categories: [
      "Cloud Computing & DevOps",
      "Software Architecture & Design Patterns",
    ],
    uploadDate: "2024-03-18",
  },
  {
    id: "79",
    title: "Learning Python",
    platform: "LinkedIn Learning",
    description:
      "An introductory course on Python, covering the basics and fundamental programming concepts.",
    link: "https://www.linkedin.com/learning/learning-python",
    rating: "Recommend",
    recommendCount: 105,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Joe Marini",
    categories: [
      "Programming Languages & Software Engineering",
      "IT Fundamentals & Support",
    ],
    uploadDate: "2024-01-29",
  },
  {
    id: "80",
    title: "The Complete Oracle SQL Certification Course",
    platform: "Udemy",
    description:
      "Prepare for Oracle SQL certification with comprehensive coverage of SQL and database management.",
    link: "https://www.udemy.com/course/the-complete-oracle-sql-certification-course/",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Imtiaz Ahmad",
    categories: ["Databases & Big Data", "IT Fundamentals & Support"],
    uploadDate: "2024-02-21",
  },
  {
    id: "81",
    title: "Complete React Developer in 2024 (w/ Redux, Hooks, GraphQL)",
    platform: "Udemy",
    description:
      "Become a proficient React developer by mastering React, Redux, Hooks, GraphQL, Context API, and more.",
    link: "https://www.udemy.com/course/complete-react-developer-zero-to-mastery/",
    rating: "Recommend",
    recommendCount: 180,
    doNotRecommendCount: 15,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrei Neagoie",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-01-16",
  },
  {
    id: "82",
    title: "Python and Django Full Stack Web Developer Bootcamp",
    platform: "Udemy",
    description:
      "Learn to build websites with Python and Django, from basic setup to deploying complex web applications.",
    link: "https://www.udemy.com/course/python-and-django-full-stack-web-developer-bootcamp/",
    rating: "Recommend",
    recommendCount: 140,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Portilla",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-04-06",
  },
  {
    id: "83",
    title: "AWS Certified Developer - Associate 2024",
    platform: "Udemy",
    description:
      "Prepare for the AWS Developer Associate certification with this comprehensive guide on AWS services and development.",
    link: "https://www.udemy.com/course/aws-certified-developer-associate/",
    rating: "Recommend",
    recommendCount: 130,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Stephane Maarek",
    categories: [
      "Cloud Computing & DevOps",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-18",
  },
  {
    id: "84",
    title: "Learn and Understand NodeJS",
    platform: "Udemy",
    description:
      "Get a deep understanding of Node.js, covering its internals, V8, the event loop, streams, and more.",
    link: "https://www.udemy.com/course/understand-nodejs/",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Anthony Alicea",
    categories: [
      "Programming Languages & Software Engineering",
      "Web Development",
    ],
    uploadDate: "2024-03-20",
  },
  {
    id: "85",
    title: "Modern Big Data Analysis with SQL Specialization",
    platform: "Coursera",
    description:
      "Master SQL for big data, including advanced querying techniques, analytics, and cloud databases.",
    link: "https://www.coursera.org/specializations/modern-big-data-analysis-with-sql",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Cloudera",
    categories: ["Databases & Big Data", "Data Science & Analytics"],
    uploadDate: "2024-04-27",
  },
  {
    id: "86",
    title: "The Complete Web Developer in 2024: Zero to Mastery",
    platform: "Udemy",
    description:
      "Learn to code and become a web developer with this complete guide on HTML, CSS, JavaScript, and more.",
    link: "https://www.udemy.com/course/the-complete-web-developer-zero-to-mastery/",
    rating: "Recommend",
    recommendCount: 160,
    doNotRecommendCount: 22,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Andrei Neagoie",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-07",
  },
  {
    id: "87",
    title: "Introduction to Quantum Computing",
    platform: "Coursera",
    description:
      "Explore the fundamentals of quantum computing, including qubits, superposition, and quantum algorithms.",
    link: "https://www.coursera.org/learn/quantum-computing",
    rating: "Depends",
    recommendCount: 65,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Toronto",
    categories: [
      "Specialized Computer Science Topics",
      "Artificial Intelligence & Machine Learning",
    ],
    uploadDate: "2024-02-03",
  },
  {
    id: "88",
    title: "Google IT Support Professional Certificate",
    platform: "Coursera",
    description:
      "Gain foundational IT skills and prepare for a career in IT support with Google's professional certificate.",
    link: "https://www.coursera.org/professional-certificates/google-it-support",
    rating: "Recommend",
    recommendCount: 150,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Google",
    categories: ["IT Fundamentals & Support", "Cybersecurity & Networking"],
    uploadDate: "2024-04-25",
  },
  {
    id: "89",
    title: "Data Visualization with Python",
    platform: "LinkedIn Learning",
    description:
      "Learn to create compelling data visualizations using Python libraries like Matplotlib and Seaborn.",
    link: "https://www.linkedin.com/learning/data-visualization-with-python",
    rating: "Recommend",
    recommendCount: 90,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Madecraft",
    categories: [
      "Data Science & Analytics",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-05-16",
  },
  {
    id: "90",
    title: "Full-Stack Web Development with Vue.js and Node.js",
    platform: "Udemy",
    description:
      "Become a full-stack developer by building applications using Vue.js on the frontend and Node.js on the backend.",
    link: "https://www.udemy.com/course/full-stack-web-development-with-vuejs-and-nodejs/",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Chris Sev",
    categories: [
      "Web Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-02-25",
  },
  {
    id: "91",
    title: "Kotlin for Android Development",
    platform: "Udemy",
    description:
      "Learn Android app development with Kotlin, focusing on creating robust and modern mobile applications.",
    link: "https://www.udemy.com/course/kotlin-for-android-development/",
    rating: "Recommend",
    recommendCount: 75,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Vasiliy Zukanov",
    categories: [
      "Mobile App Development",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-01-13",
  },
  {
    id: "92",
    title: "The Complete Machine Learning Course with Python",
    platform: "Udemy",
    description:
      "Master machine learning concepts and build projects using Python and popular libraries like scikit-learn.",
    link: "https://www.udemy.com/course/machine-learning-with-python/",
    rating: "Recommend",
    recommendCount: 140,
    doNotRecommendCount: 18,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Kirill Eremenko",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-04-11",
  },
  {
    id: "93",
    title: "Introduction to Natural Language Processing",
    platform: "Coursera",
    description:
      "Learn the basics of natural language processing, including text processing, sentiment analysis, and machine learning.",
    link: "https://www.coursera.org/learn/natural-language-processing",
    rating: "Recommend",
    recommendCount: 80,
    doNotRecommendCount: 9,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "National Research University Higher School of Economics",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-02-17",
  },
  {
    id: "94",
    title: "The Ultimate MySQL Bootcamp: Go from SQL Beginner to Expert",
    platform: "Udemy",
    description:
      "Master MySQL and learn to build complex SQL queries and database-driven applications.",
    link: "https://www.udemy.com/course/the-ultimate-mysql-bootcamp-go-from-sql-beginner-to-expert/",
    rating: "Recommend",
    recommendCount: 95,
    doNotRecommendCount: 11,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Colt Steele",
    categories: [
      "Databases & Big Data",
      "Programming Languages & Software Engineering",
    ],
    uploadDate: "2024-03-24",
  },
  {
    id: "95",
    title: "Introduction to Cybersecurity Specialization",
    platform: "Coursera",
    description:
      "Gain essential cybersecurity skills, including threat analysis, protection strategies, and incident response.",
    link: "https://www.coursera.org/specializations/intro-cyber-security",
    rating: "Recommend",
    recommendCount: 85,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "University of Washington",
    categories: ["Cybersecurity & Networking", "IT Fundamentals & Support"],
    uploadDate: "2024-05-01",
  },
  {
    id: "96",
    title: "Azure DevOps Fundamentals for Beginners",
    platform: "Udemy",
    description:
      "Learn the basics of Azure DevOps, including version control, pipelines, and release management.",
    link: "https://www.udemy.com/course/azure-devops-fundamentals-for-beginners/",
    rating: "Recommend",
    recommendCount: 70,
    doNotRecommendCount: 8,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Alan Rodrigues",
    categories: ["Cloud Computing & DevOps", "IT Fundamentals & Support"],
    uploadDate: "2024-02-22",
  },
  {
    id: "97",
    title: "Java Programming: Solving Problems with Software",
    platform: "Coursera",
    description:
      "Learn Java programming by solving real-world problems and building software from scratch.",
    link: "https://www.coursera.org/learn/java-programming",
    rating: "Recommend",
    recommendCount: 100,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Duke University",
    categories: ["Programming Languages & Software Engineering"],
    uploadDate: "2024-03-22",
  },
  {
    id: "98",
    title: "Complete Guide to TensorFlow for Deep Learning with Python",
    platform: "Udemy",
    description:
      "Master TensorFlow and build neural networks and deep learning models using Python.",
    link: "https://www.udemy.com/course/complete-guide-to-tensorflow-for-deep-learning-with-python/",
    rating: "Recommend",
    recommendCount: 120,
    doNotRecommendCount: 12,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Jose Portilla",
    categories: [
      "Artificial Intelligence & Machine Learning",
      "Data Science & Analytics",
    ],
    uploadDate: "2024-01-19",
  },
  {
    id: "99",
    title: "Understanding TypeScript - 2024 Edition",
    platform: "Udemy",
    description:
      "Learn TypeScript from scratch, including how to use it effectively in modern web development.",
    link: "https://www.udemy.com/course/understanding-typescript/",
    rating: "Recommend",
    recommendCount: 130,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "Maximilian Schwarzmüller",
    categories: [
      "Programming Languages & Software Engineering",
      "Web Development",
    ],
    uploadDate: "2024-04-04",
  },
  {
    id: "100",
    title: "The Complete Networking Fundamentals Course",
    platform: "Udemy",
    description:
      "Understand the basics of networking, including protocols, routing, switching, and more.",
    link: "https://www.udemy.com/course/the-complete-networking-fundamentals-course/",
    rating: "Recommend",
    recommendCount: 75,
    doNotRecommendCount: 10,
    thumbnail: "https://via.placeholder.com/150",
    instructor: "David Bombal",
    categories: ["Cybersecurity & Networking", "IT Fundamentals & Support"],
    uploadDate: "2024-03-14",
  },
];
